enum IpcProviderResourceEnums {
    GET_PROJECT_LIST= "GET_PROJECT_LIST",
    SET_ACTIVE_PROJECT_FROM_FILEPICKER= "SET_ACTIVE_PROJECT_FROM_FILEPICKER",
    SET_ACTIVE_PROJECT_FROM_LIST= "SET_ACTIVE_PROJECT_FROM_LIST",
    GET_RESOURCE_LIST= "GET_RESOURCE_LIST",
    GET_TAG_LIST= "GET_TAG_LIST",






    REMOVE_PROJECT_FROM_LIST= "REMOVE_PROJECT_FROM_LIST",
    SET_PROJECT= "SET_PROJECT",
    SAVE_PROJECT= "SAVE_PROJECT",
    CREATE_PROJECT= "CREATE_PROJECT",
    LOAD_PROJECT= "LOAD_PROJECT",
    EXECUTE_RESOURCE= "EXECUTE_RESOURCE",
    REGISTER_RESOURCE_CHANGE_LISTENER = "REGISTER_RESOURCE_CHANGE_LISTENER",
    ON_RESOURCE_CHANGE = "ON_RESOURCE_CHANGE",
    TRIGGER_SET_PROJECT = "TRIGGER_SET_PROJECT",
    TRIGGER_TAGS_MANAGER= "TRIGGER_TAGS_MANAGER",


    UPDATE_RESOURCE = "UPDATE_RESOURCE",
    REMOVE_RESOURCE = "REMOVE_RESOURCE",
    SAVE_TAG_LIST = "SAVE_TAG_LIST",
    REMOVE_TAG = "REMOVE_TAG"





}
export default IpcProviderResourceEnums;
