enum IpcProviderResourceEnums {
    SET_PROJECT= "SET_PROJECT",
    IS_EXIST_PROJECT= "IS_EXIST_PROJECT",
    GET_PROJECT= "GET_PROJECT",
    SAVE_PROJECT= "SAVE_PROJECT",
    CREATE_PROJECT= "CREATE_PROJECT",
    LOAD_PROJECT= "LOAD_PROJECT",
    EXECUTE_RESOURCE= "EXECUTE_RESOURCE",
    GET_LIST_RESOURCE= "GET_LIST_RESOURCE",
    GET_THUMBNAIL= "GET_THUMBNAIL",
    SET_LOADER_MESSAGE= "SET_LOADER_MESSAGE"
}
export default IpcProviderResourceEnums;
