enum IpcProviderResourceEnums {
    SET_PROJECT= "SET_PROJECT",
    GET_PROJECT= "GET_PROJECT",
    SAVE_PROJECT= "SAVE_PROJECT",
    CREATE_PROJECT= "CREATE_PROJECT",
    LOAD_PROJECT= "LOAD_PROJECT",
    EXECUTE_RESOURCE= "EXECUTE_RESOURCE",
    RUN_THUMBNAIL_CHANGE = "RUN_THUMBNAIL_CHANGE",
    ON_THUMBNAIL_CHANGE = "ON_THUMBNAIL_CHANGE",
    TRIGGER_SET_PROJECT = "TRIGGER_SET_PROJECT",
    TRIGGER_TAGS_MANAGER= "TRIGGER_TAGS_MANAGER"
}
export default IpcProviderResourceEnums;
